### ISSUE TITLE
Instance: The Unmarked Trail

### ISSUE THREAD

**Issue by dawnz85** [echoes-emu/echoes-bt#382]
Post all issues related to this instance here.

**Comment by dawnz85** [comment]
Legolas doesn't attack when he's in melee range.

**Comment by dawnz85** [comment]
Legolas should change targets to help with the root adds on Caller of the Bog. At present he remains on the boss when the boss becomes an NPCs.

**Comment by bcp19** [comment]
> Legolas doesn't attack when he's in melee range.

This issue is fixed, but the other two still need work

**Comment by bcp19** [comment]
Just noticed on Live that there is a cutscene after finishing this instance that is missing on here

**Comment by woodx319** [comment]
> ~Just noticed on Live that there is a cutscene after finishing this instance that is missing on here~

Looks like the cutscene is in after the instance. 

Legolas still looks to kneel at times. was very quick and happened to me 2-3 times during the instance. 
Legolas still does not engage adds during caller of bog fight.
